### PR TITLE
Support for 480x320 screens

### PR DESCRIPTION
**Pull request by redion1992**
As discussed in issue #26. I've also modified the backend code to have a switch for extended text messages.

### CODE REVIEW

**Comment by redion1992** [comment]
For some reason, the movement of the .ino sketch didn't show up properly in GitHub, registering as a deletion and creation.

**Comment by Grimzentide** [comment]
wow... will try and review the pull request and accept it in the next 24 hours.  Need to see how it affects the unreleased version.

Thanks for your on-going commitment ...

**Comment by redion1992** [comment]
IF there's stuff that gets in the way of the unreleased version, focus on getting that going. I can maintain the upsized-screen support after the fact. The only major changes made that aren't on a compile-time switch is to minimise the size of the function that draws the tire wear. I can refactor that again afterwards if the need is there.

**Comment by Grimzentide** [comment]
Setting the HDGFX switch to false causes the following problems on a 2.8" screen. Was I wrong in assuming that this code would work for both 2.8 and 3.6 inch screens?

img_0962

**Comment by redion1992** [comment]
No, the intention was to simply have it work for 320x240 on HDGFX being set to false. Don't merge this for now, I'll do some working on it and figure out what's going on.

**Comment by redion1992** [comment]
Well, the first major issue was that I forgot to wrap some of the changes I'd made to get it working (rotation, inverting colour palette) in #ifdef statements. Fixed those, and I'll debug some more on the hardware I have.

**Comment by redion1992** [comment]
Derp. Every single check in the code is testing whether HDGFX **exists**, not whether it's set to true or false. So even if it's set to false in the header, the code is acting as if it was meant to be set to true.

**Comment by redion1992** [comment]
Also, I'm going to separate the pull requests out - one for the tweaks to the backend, and one for the Arduino code.

**Pull request closed without merging**
